version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  mongo-data:
    